### ISSUE TITLE
Taking a portrait photo uploads the photo, but it's rotated 90 degrees

### ISSUE THREAD

**Issue by cerupcat** [filestack/FSPicker#12]
When I take a photo in portrait, when I view the photo back in the app it's rotate 90 degrees instead of in portrait.

**Comment by cerupcat** [comment]
Adding the `fixImageRotationIfNecessary` method from here fixes it:

https://github.com/Ink/ios-picker/blob/69689e4338b9b50a8b5118f49ae5126719200e69/FPPicker/Platforms/iOS/FPUtils%2BiOS.m

I don't know the best place to add it in the current codebase, so I'll let you do that.

**Comment by pJes2** [comment]
thanks for the report - I'll release new version this week, with this issue fixed.
