### ISSUE TITLE
Taking a photo upload a png instead of jpg 

### ISSUE THREAD

**Issue by cerupcat** [filestack/FSPicker#13]
In `FSSourceListViewController`, after taking a photo the NSData is a png `UIImagePNGRepresentation`, but the extension added is `.jpg`. Since camera images don't have transparency, using UIImageJPEGRepresentation instead should allow uploading significantly faster. I tested and it's 2-3 times faster to upload using UIImageJPEGRepresentation at full quality.

**Comment by pJes2** [comment]
Hi @cerupcat sorry for a late response, I was on vacation.
Thanks for the catch - I'll release new version with fix this week
