### ISSUE TITLE
FSSourceListViewControlller.title should be configurable

### ISSUE THREAD

**Issue by dbaq** [filestack/FSPicker#18]
Hello,

Please allow the title of `FSSourceListViewControlller` to be configurable, like it is on the android SDK.

https://github.com/filestack/FSPicker/blob/3a7f0a49b5ca078d9286262cf24e38820317afa6/FSPicker/Platforms/iOS/ViewControllers/FSSourceListViewController.m#L114

Thank you.

**Comment by pJes2** [comment]
Added in `1.1.2`.
