### ISSUE TITLE
Manual integration

### ISSUE THREAD

**Issue by vishalvshekkar** [filestack/FSPicker#20]
Can please you give an instruction for manual integration of FSPicker in iOS? We are not using Cocoapods in our project and it would help a great deal if you could give the steps for manually installing FSPicker.

**Comment by rnine** [comment]
@vishalvshekkar Manual integration is not currently supported since `FSPicker` has dependencies managed by CocoaPods. In this specific case, `FSPicker` depends on `Filestack` which itself depends on `AFNetworking`.
