### ISSUE TITLE
Problem cause by manually setting the top inset of the FSSourceTableViewController

### ISSUE THREAD

**Issue by jjdddn1** [filestack/FSPicker#21]
I saw the logic in FSSourceTableViewController is to calculate the bottom of nav bar and set a topInset for the table accordingly.

But this only works fine when the nav bar is translucent. If I want to make it not translucent, then it will leave a blank between the nav bar and the table. 

Btw even the nav bar is translucent, the scroll indicator still start from the top of the nav bar... rather than the top of the first cell/header view.

We are using your product and this problem did cause some trouble. A fix would be more than appreciated!

**Comment by rnine** [comment]
@jjdddn1 Could you share some code that showcases the issue you are describing? Alternatively, could you describe the steps needed to replicate the issue? Thanks!

**Comment by jjdddn1** [comment]
After you add:
 _filePickerController.navigationBar.translucent = NO;

Here is what it looks like:
https://gyazo.com/56526b9cd5de0964e0a57977d7d59aaf.png

**Comment by rnine** [comment]
@jjdddn1 Thank you, I can confirm the issue is there. I have included a fix for it in https://github.com/filestack/FSPicker/commit/2b749af1cafce0e84476ecf71ac472c4d481b796 — can you confirm it works for you?

You can test the latest code locally by using the develop branch:

1. In your `Podfile`:
```
pod "FSPicker", git: 'https://github.com/filestack/FSPicker.git', branch: 'develop'
```

2. `pod install`

**Comment by jjdddn1** [comment]
Yes! It solved this problem! Thanks so much!

**Comment by rnine** [comment]
@jjdddn1 Thank you for reporting! We'll include this fix in the next stable release, meanwhile you can continue using the develop branch 👍
