### ISSUE TITLE
Table cell are not deselected correctly.

### ISSUE THREAD

**Issue by jjdddn1** [filestack/FSPicker#22]
When uploading, with multi-select set to NO, if I tap on a doc for a long time and release, the cell will not be deselected until I tap on it again. 

May need a [self.tableViewController reloadData] or something similar at the end of uploadSelectedContents() in FSSourceViewController.

**Comment by rnine** [comment]
@jjdddn1 I am unable to reproduce this issue using the latest FSPicker following the steps you are describing. 

Can you reproduce this problem in a fresh project? If so, could you share the code?

Thanks!

**Comment by jjdddn1** [comment]
Sorry forget about this one. It works fine right now.
