### ISSUE TITLE
After signing in with google, screen is getting stuck

### ISSUE THREAD

**Issue by philolo1** [filestack/FSPicker#25]
After signing in with google i can enter my email and see the next screen, but now , the screen shows a loading progress but now its showing the loading state and not doing anytihng. IF i go back and forth it seems to work.

<img width="327" alt="screen shot 2017-06-02 at 6 40 57 pm" src="https://cloud.githubusercontent.com/assets/6276582/26720417/2bde8d60-47c3-11e7-97ef-21efc3218b61.png">

**Comment by philolo1** [comment]
by back and forth i mean clicking the 'Back' button

**Comment by rnine** [comment]
@philolo1 Are you still having issues with this in the latest release(s)? I think this issue was fixed in v1.1.7.
