### ISSUE TITLE
Can not login into Amazon Cloud

### ISSUE THREAD

**Issue by jjdddn1** [filestack/FSPicker#26]
I updated to 1.1.4 and I'm still not able to log into my Amazon Cloud account.
I'm in US and the response url start with https://na.account.amazon.com/ap/return?arb=16....
which is not in your fsAllowedUrlPrefix.plist list...

**Comment by rnine** [comment]
@jjdddn1 Can you confirm this works for you in the latest release (currently v1.1.6)?

**Comment by jjdddn1** [comment]
It works! Thanks so much!
