### ISSUE TITLE
When didFinisheDPickingMediaWithBlobs is called dismissViewControllerAnimated doesn't dismiss view

### ISSUE THREAD

**Issue by cerupcat** [filestack/FSPicker#3]
After calling `didFinishedPickingMediaWithBlobs`, I call 

```
    [picker dismissViewControllerAnimated:YES completion:nil];
```

but the viewcontroller is still there.

This is likely due to `didFinishedPickingMediaWithBlobs` being called prior to the loading viewcontroller being dismissed.

**Comment by pJes2** [comment]
@cerupcat please check new version (0.1.2)
