### ISSUE TITLE
Setting config.selectMultiple = NO not working

### ISSUE THREAD

**Issue by cerupcat** [filestack/FSPicker#5]
Setting the `config.selectMultiple = NO` still allows selecting multiple images. If I set the maxSelected to 1, it only allows settings 1, but doesn't auto-upload like previous filepicker.

**Comment by pJes2** [comment]
@cerupcat please check new version (0.1.2)

Also, if you have any feature requests or you have found some bugs, please, as before, open an issue and I'll try to add/fix them for you.

**Comment by cerupcat** [comment]
Thanks, everything is looking good so far.
