### ISSUE TITLE
Module 'FSPicker' not found

### ISSUE THREAD

**Issue by Johnnycon** [filestack/FSPicker#6]
Hi there - happy to see the UI part of this project on it's way to release.  I'm having issues integrating this project into my existing project or a brand new project.  I had no issues integrating the Filestack pod, but this one is giving issues. I keep getting the "Module 'FSPicker' not found" error.  

I'm using XCode 7.3.1 (objective-c) and targeting iOS 9.0.  I've got the latest cocoapods installed.  I've tried using the @import FSPicker syntax, the #import "FSPicker.h" syntax, but just can't seem to get this project running.  I can also import Filestack when I only include the FSPicker pod so I assume it's loading fine, I'm just not able to import the FSPicker module. 

Is it possible there's a step missing from the instructions?

**Comment by pJes2** [comment]
Hi @JohnnyCon I've released small fix adding missing FSPicker.h file.

Before the fix you could do `#import <FSPicker/FSPickerController.h>` to import FSPicker, but after the fix (for naming consistency) import it like this: `#import <FSPicker/FSPicker.h>`

`@import FSPicker;` should also work, but you may encounter an issue described here:
http://stackoverflow.com/questions/29620786/import-causes-parse-issue-could-not-build-module

**Comment by Johnnycon** [comment]
Thank you, that worked.  Ended up using the:
#import <FSPicker/FSPicker.h> syntax
