### ISSUE TITLE
Crash when selecting web images

### ISSUE THREAD

**Issue by cerupcat** [filestack/FSPicker#8]
On line 349 of FSSearchViewController.m crashes when selecting multiple images for upload.

```
2016-05-16 16:47:19.210 Employers[2968:828801] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x146d365f0> was mutated while being enumerated.'
```

**Comment by cerupcat** [comment]
I'm not sure this is even necessary. Removing this fixes the crash.

```
    for (NSIndexPath *indexPath in self.selectedIndexPaths) {
        [self collectionView:self.collectionView didDeselectItemAtIndexPath:indexPath];
    }
```

**Comment by pJes2** [comment]
please try version `0.1.4-beta`.

This 3 lines are necessary to clear the selection and keep the "upload behaviour" consistent across the different controllers
