### ISSUE TITLE
Crash when selecting multiple images from photos page

### ISSUE THREAD

**Issue by cerupcat** [filestack/FSPicker#9]
On  line 151 of FSGridViewController it also crashes on 

```
    for (NSIndexPath *indexPath in self.selectedIndexPaths) {
```

I think there may be one or two other places that also iterates of selectedIndexPaths in this way. So, the fix should apply to all of them.

**Comment by pJes2** [comment]
Oh boy I really did miss that one - version `0.1.5-beta` should fix that. ;)
